# These are supported funding model platforms

github: riolubruh
patreon: 
open_collective: # Replace with a single Open Collective username
ko_fi: riolubruh
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
custom: ["https://venmo.com/riolubruh", "https://cash.app/$riolubruh", "https://www.paypal.com/donate/?hosted_button_id=U5PZFBNGKSGFQ"]
